trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: UseDotNet@2
  displayName: .NET Version
  inputs:
    packageType: 'sdk'
    version: '6.0.400-preview.22330.6'

- task: Bash@3
  displayName: Install MAUI
  inputs:
   targetType: 'inline'
   script: |
          dotnet nuget locals all --clear 
          dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'src/UFO/UFO.csproj'
    arguments: '-c Release'
